import fs from 'node:fs/promises';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { atomicWrite } from '../utils/fs.js';
import { logger, SkitError } from '../utils/logger.js';
import type { SkillPackageJson } from '../types/skill.js';

const PKG_JSON = 'package.json';

// 读取 package.json;不存在返回 null
export async function readPackageJson(skillPath: string): Promise<SkillPackageJson | null> {
    const file = path.join(skillPath, PKG_JSON);
    try {
        const raw = await fs.readFile(file, 'utf-8');
        return JSON.parse(raw) as SkillPackageJson;
    } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        if (err instanceof SyntaxError) {
            throw new SkitError('E_INVALID_SKILL', `package.json 解析失败: ${(err as Error).message}`);
        }
        throw err;
    }
}

// 写入 package.json(原子写入)
export async function writePackageJson(skillPath: string, pkg: SkillPackageJson): Promise<void> {
    await atomicWrite(path.join(skillPath, PKG_JSON), JSON.stringify(pkg, null, 2) + '\n');
}

// 获取 git user.name 作为 author 兜底
function gitUserName(): string | undefined {
    try {
        return execSync('git config user.name', { encoding: 'utf-8' }).trim() || undefined;
    } catch {
        return undefined;
    }
}

// 确保 skill 目录下有 package.json;缺失则自动生成
// 返回 { pkg, generated } — generated=true 表示本次自动生成
export async function ensureManifest(
    skillPath: string,
    opts: { source?: string; fallbackName?: string; fallbackDescription?: string }
): Promise<{ pkg: SkillPackageJson; generated: boolean }> {
    const existing = await readPackageJson(skillPath);
    if (existing) {
        // 补全 skkill 字段
        if (opts.source && !existing.skkill?.source) {
            existing.skkill = { ...existing.skkill, source: opts.source, installedAt: new Date().toISOString() };
            await writePackageJson(skillPath, existing);
        }
        return { pkg: existing, generated: false };
    }

    // 自动生成
    const author = gitUserName();
    const generated: SkillPackageJson = {
        name: opts.fallbackName ?? path.basename(skillPath),
        version: '0.1.0',
        description: opts.fallbackDescription ?? 'Auto-generated by skkill',
        ...(author ? { author } : {}),
        skkill: {
            ...(opts.source ? { source: opts.source } : {}),
            installedAt: new Date().toISOString(),
        },
    };
    await writePackageJson(skillPath, generated);
    logger.warn(`Auto-generated package.json for "${generated.name}"; consider upstreaming.`);
    return { pkg: generated, generated: true };
}
